# versi docker compose yg dipakai 3.7
version: '3.7'
services:
  our-rest-api: 
    container_name: our-rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - 8000:8000